### ISSUE TITLE
KeyError: 'pigment'

### ISSUE THREAD

**Issue by ssssskyeeeee** [ModelSEED/ModelSEEDpy#151]
When I run the model reconstruction code, I always get an error message saying that the pigment key is error, can it help me solve the problem

>>> from modelseedpy import MSBuilder, MSGenome
>>> from modelseedpy.helpers import get_template
>>> from modelseedpy.core.mstemplate import MSTemplateBuilder
>>> template = MSTemplateBuilder.from_dict(get_template('template_core')).build()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/luluotian/application/modelseed/ModelSEEDpy/modelseedpy/core/mstemplate.py", line 1636, in build
    list(
  File "/public/home/luluotian/application/modelseed/ModelSEEDpy/modelseedpy/core/mstemplate.py", line 1637, in <lambda>
    map(lambda x: MSTemplateBiomass.from_dict(x, template), self.biomasses)
  File "/public/home/luluotian/application/modelseed/ModelSEEDpy/modelseedpy/core/mstemplate.py", line 646, in from_dict
    d["pigment"],
KeyError: 'pigment'

**Comment by Fxe** [comment]
Thanks for reporting, we will post a fix later this week!
